feat: Add file menu et menu editor option for copy url
kometenstaub/copy-publish-url pull request #1
Opened 2021-11-25 12:00 UTC by Mara-Li

I think it will be practical to have this option.

Also, do you have think about to don't show the modal if publish = false, instead of an error message?

2021-11-25 15:30 UTC, kometenstaub commented
> I think it will be practical to have this option.

I see that you already forked this repo and added these features. Feel free to make a PR, but please let the file menu and editor options be off by default, so that they can be enabled in the settings. I don't want to clutter these menus any more than necessary.
So one toggle in the settings for the file menu and another one for the editor menu.


> Also, do you have think about to don't show the modal if publish = false, instead of an error message?

That is by design. If it didn't show anything, then the user might not know that the status is set to false and could think that the plugin doesn't work. (Only tags and aliases are shown by default in preview mode.)
I also see it as a kind of warning.

2021-11-25 15:32 UTC, kometenstaub commented
Sorry, I just realised that this was already the PR.

Please let the file menu and editor options be off by default, so that they can be enabled in the settings. I don't want to clutter these menus any more than necessary.
So one toggle in the settings for the file menu and another one for the editor menu.

2021-11-25 15:38 UTC, kometenstaub requested changes

2021-11-25 15:38 UTC, kometenstaub commented on src/main.ts
> +        this.registerEvent(this.app.workspace.on("file-menu", (menu, file : TFile) => {
Please only add this if the user enabled them in the settings. (Off by default.)

2021-11-25 15:38 UTC, kometenstaub commented on src/main.ts
> +        this.registerEvent(this.app.workspace.on("editor-menu", (menu, editor, view) => {
Same thing here.

2021-11-25 15:38 UTC, kometenstaub commented on src/main.ts
> +            "checkCallback": (checking: boolean) => {
```suggestion
            id: 'copy-publish-url',
            name: 'Copy URL',
            checkCallback: (checking: boolean) => {
```

2021-11-25 15:39 UTC, kometenstaub commented on src/main.ts
> +            "checkCallback": (checking: boolean) => {
That's just a style thing.

2021-11-25 17:05 UTC, Mara-Li commented
I completely understand for the option, and I think it's a good idea !

2021-11-25 18:02 UTC, Mara-Li commented
Normally, it's all good !

2021-11-27 12:10 UTC, kometenstaub requested changes
1. Please only register the two events when the setting is turned on. Currently they're getting registered even when the toggle is off, they just don't get added to the menus because of the condition check.
2. It only works if a note has `publish: true`. It shouldn't be in the menu if the note contains `publish: false`, that's correct. However, it should still appear if the `publish` flag hasn't been explicitly set to `true`.
3. Please implement two toggles, one for the editor menu, the other one for the file menu.
4. Regarding the icon, would it make more sense to use the same icon Obsidian uses for copying instead of using the paste icon? 
![image](https://user-images.githubusercontent.com/83140328/143680705-bdc2fae2-7d53-426f-8661-0ad5edd8cf95.png)
5. For the other changes, please refer to the comments I have added to the lines.

2021-11-27 12:10 UTC, kometenstaub commented on src/main.ts
>      publishPath: '',
Please add `enableContext` with a value of `false` here.

2021-11-27 12:10 UTC, kometenstaub commented on src/main.ts
> +        this.registerEvent(this.app.workspace.on("editor-menu", (menu, editor, view) => {
You're registering the `editor-menu` twice, but it should only appear once.

2021-11-27 12:10 UTC, kometenstaub commented on src/settings.ts
> +                toggle.onChange(value =>{
Please make this async. `saveSettings()` calls `saveData()`, [which is async](https://github.com/obsidianmd/obsidian-api/blob/5687a75ecfdb78b6a832127cf6f9229e27e196a0/obsidian.d.ts#L2345).

2021-11-28 12:10 UTC, Mara-Li commented
> 1. Please only register the two events when the setting is turned on. Currently they're getting registered even when the toggle is off, they just don't get added to the menus because of the condition check.

I can do that, but it force to user to always reload the plugin if they change settings. I don't think it's a good idea. It's also the same for unload, so I "invisible" the menu in case the settings is take of.
Also, I added information about reload plugin in the description option. It's up to you to keep it or remove it. 

>     2. It only works if a note has `publish: true`. It shouldn't be in the menu if the note contains `publish: false`, that's correct. However, it should still appear if the `publish` flag hasn't been explicitly set to `true`.
Done! 

>     3. Please implement two toggles, one for the editor menu, the other one for the file menu.
In fact, I was thinking that "editor menu" was for an option in context menu when a file is open, and 'file-menu' for a right click in the explorer. I realize now that is the right click **on** a file, as for copy, paste, … 
I removed this option, I don't think it's the right place to add the plugin!

>     4. Regarding the icon, would it make more sense to use the same icon Obsidian uses for copying instead of using the paste icon?
>        ![image](https://user-images.githubusercontent.com/83140328/143680705-bdc2fae2-7d53-426f-8661-0ad5edd8cf95.png)

I think the `link` icon is better because Obsidian use it for "copy Obsidian URL".

2021-11-28 12:42 UTC, Mara-Li reviewed
Everything requested is done

2021-11-28 22:14 UTC, merged

2021-11-28 22:19 UTC, kometenstaub commented
> I can do that, but it force to user to always reload the plugin if they change settings. I don't think it's a good idea. It's also the same for unload, so I "invisible" the menu in case the settings is take of.
> Also, I added information about reload plugin in the description option. It's up to you to keep it or remove it.

I took care of that, the plugin is now automatically reloaded when the button is toggled (the settings page for this plugin is automatically reopened as well).

I also refactored the code so that both the command and the menu entry re-use the same code.

Thanks for your work on this! :)
The changes are released in 0.2.0

2021-11-29 11:14 UTC, Mara-Li commented
Thank you ! 🎉